In [16]:
import numpy as np
import pandas as pd
import matplotlib as mpl
from matplotlib import pyplot as plt

In [17]:

df = pd.read_csv('dataset\heart.csv')
shuffled = df.sample(frac=1.0, replace=False)
df = shuffled.reset_index(drop = True)
df['x0'] = 1
df.head(20)

<>:1: SyntaxWarning: invalid escape sequence '\h'
<>:1: SyntaxWarning: invalid escape sequence '\h'
C:\Users\kumar\AppData\Local\Temp\ipykernel_11208\2668772640.py:1: SyntaxWarning: invalid escape sequence '\h'
  df = pd.read_csv('dataset\heart.csv')

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,x0
0,52,0,2,136,196,0,0,169,0,0.1,1,0,2,1,1
1,66,1,0,112,212,0,0,132,1,0.1,2,1,2,0,1
2,54,1,1,108,309,0,1,156,0,0.0,2,0,3,1,1
3,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1,1
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0,1
5,59,1,3,178,270,0,0,145,0,4.2,0,0,3,1,1
6,57,1,0,152,274,0,1,88,1,1.2,1,1,3,0,1
7,40,1,0,110,167,0,0,114,1,2.0,1,0,3,0,1
8,66,1,1,160,246,0,1,120,1,0.0,1,3,1,0,1
9,48,1,2,124,255,1,1,175,0,0.0,2,2,2,1,1
10,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0,1
11,39,0,2,94,199,0,1,179,0,0.0,2,0,2,1,1
12,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1,1
13,53,1,2,130,197,1,0,152,0,1.2,0,0,2,1,1
14,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1,1
15,51,1,0,140,261,0,0,186,1,0.0,2,0,2,1,1
16,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1,1
17,56,1,1,130,221,0,0,163,0,0.0,2,0,3,1,1
18,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0,1
19,44,1,2,120,226,0,1,169,0,0.0,2,0,2,1,1

In [18]:
x = df.drop(['target'], axis= 1)
y = df.target
y

0      1
1      0
2      1
3      1
4      0
      ..
298    1
299    0
300    1
301    1
302    1
Name: target, Length: 303, dtype: int64

In [19]:
x_train, x_test = x[0:240], x[241:]
y_train, y_test = y[0:240], y[241:]
x_test.head(30)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,x0
241,62,0,0,150,244,0,1,154,1,1.4,1,0,2,1
242,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1
243,60,0,0,150,258,0,0,157,0,2.6,1,2,3,1
244,56,0,0,134,409,0,0,150,1,1.9,1,2,3,1
245,61,1,0,148,203,0,1,161,0,0.0,2,1,3,1
246,67,1,0,120,237,0,1,71,0,1.0,1,0,2,1
247,39,0,2,138,220,0,1,152,0,0.0,1,0,2,1
248,44,1,2,140,235,0,0,180,0,0.0,2,0,2,1
249,40,1,0,152,223,0,1,181,0,0.0,2,0,3,1
250,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
251,38,1,3,120,231,0,1,182,1,3.8,1,0,3,1
252,63,1,0,130,254,0,0,147,0,1.4,1,1,3,1
253,50,1,2,129,196,0,1,163,0,0.0,2,0,2,1
254,60,1,0,145,282,0,0,142,1,2.8,1,2,3,1
255,56,1,0,125,249,1,0,144,1,1.2,1,1,2,1
256,43,1,2,130,315,0,1,162,0,1.9,2,1,2,1
257,61,0,0,145,307,0,0,146,1,1.0,1,0,3,1
258,60,1,0,125,258,0,0,141,1,2.8,1,1,3,1
259,46,1,0,140,311,0,1,120,1,1.8,1,2,3,1
260,51,1,0,140,298,0,1,122,1,4.2,1,3,3,1
261,59,1,0,170,326,0,0,140,1,3.4,0,0,3,1
262,54,1,0,110,239,0,1,126,1,2.8,1,1,3,1
263,58,1,2,132,224,0,0,173,0,3.2,2,2,3,1
264,52,1,3,152,298,1,1,178,0,1.2,1,0,3,1
265,44,0,2,118,242,0,1,149,0,0.3,1,1,2,1
266,45,1,0,115,260,0,0,185,0,0.0,2,0,2,1
267,59,1,3,170,288,0,0,159,0,0.2,1,0,3,1
268,51,0,0,130,305,0,1,142,1,1.2,1,0,3,1
269,41,1,1,120,157,0,1,182,0,0.0,2,0,2,1
270,52,1,0,112,230,0,1,160,0,0.0,2,1,2,1

In [20]:
w = np.random.randn(x_train.shape[1])
w

array([ 1.11644268,  0.43313593, -1.65968688, -0.03869878,  0.10849277,
        0.01230679, -0.68713921, -1.45123174, -0.34676562, -0.15090471,
       -0.48678333,  0.89645903, -0.61622274, -0.79765071])

In [42]:
def hypothesis(X,w):
  z = np.dot(X.T,w)
  return 1/(1 + np.exp(-z))

In [43]:
hypothesis(x_train.iloc[1],w)

1.0

In [44]:
m,n = x_train.shape
h_test = []
for i in range(m):
  h_test.append(hypothesis(x_train.iloc[i],np.ones(n)))

In [ ]:
def log_likelihood(x,y,w):
  m,n = x.shape
  l_0 = 0
  epsilon = np.exp(-15)
  for i in range(m):
    l_0 += (y[i]*np.log(hypothesis(x_train.iloc[i],w) + epsilon) + (1 - y[i])*np.log(1 - hypothesis(x_train.iloc[i],w) + epsilon) )
  return l_0

In [26]:
def derivative(x,y,w):
  m,n = x.shape
  dL_dw = np.zeros(n)
  for i in range(m):
    error = y[i] - hypothesis(x.loc[i].values,w)
    for j in range(n):
      dL_dw[j] += error* (x.iloc[i,j])
  return dL_dw

In [27]:
der = derivative(x_train,y_train,w)

In [28]:
def derivative1(x, y, w):
    m, n = x.shape
    dL_dw = np.zeros(n)

    for j in range(n):
        error = 0.0
        for i in range(m):
            #print(y[i])
            #print(hypothesis(x.iloc[i].values, w))
            error += (y[i] - hypothesis(x.iloc[i].values, w)) * x.iloc[i, j]
        dL_dw[j] = error
    return dL_dw

In [13]:
import math

In [96]:
def logistic(x,y,w,alpha,no_iters):
  log_like_hist = [0]
  m,n = x.shape
  for i in range(no_iters):
    dl_dw = derivative1(x,y,w)
    w += dl_dw*alpha
    
    if( i < 10000):
      log_like_hist.append(log_likelihood(x,y,w))
    if i%math.ceil(no_iters/10)==0:
      print(f"iteration {i:4d} : loglikelihood {log_like_hist[-1]:8.2f}")
  return w,log_like_hist

In [97]:
alpha = 0.0001
no_iters = 100
w_final, hist_final = logistic(x_train,y_train,w,alpha,no_iters)
w_final

iteration    0 : loglikelihood -3980.82

C:\Users\kumar\AppData\Local\Temp\ipykernel_11208\4064037238.py:3: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-z))

iteration   10 : loglikelihood -3671.29
iteration   20 : loglikelihood -2376.18
iteration   30 : loglikelihood -3124.45
iteration   40 : loglikelihood -2040.00
iteration   50 : loglikelihood -2069.82
iteration   60 : loglikelihood -2784.62
iteration   70 : loglikelihood -2154.25
iteration   80 : loglikelihood -2846.56
iteration   90 : loglikelihood -2228.04

array([-2.13855752,  0.04681757, -0.68539407, -5.35002793,  0.04561559,
       -0.02743364, -0.55650255, 10.9623454 , -0.76122734, -1.07083858,
       -0.12427749, -0.03204283, -1.16633649, -0.82384097])

In [100]:
hypothesis(x_train.iloc[123],w_final)

1.0

In [68]:
def accuracy(x_test,w_final):
  count = 0
  for i in range(241,270):
    if round(hypothesis(x_test.iloc[i],w_final)) == y_test[i]:
      count += 1
  return count

In [75]:
accuracy(x_test,w_final)

IndexError: single positional indexer is out-of-bounds