In [1]:
#imports
import math
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
class SVMClassifier1:
    def __init__(self,tol = 1e-8,C = 1.0,no_passes = 10):
        self.tol = tol
        self.C = C
        self.w = None
        self.b = None
        self.max_passes = no_passes
        self.alpha = None
        self.Pos_support_vec = None
        self.neg_support_vec = None
    def pridict(self,x_i):
        return np.dot(x_i, self.w) + self.b
    def K(self,x_i,x_j):
        return np.dot(x_i.T,x_j)
    def __w__(self,x_train,y_train,alpha):
        return np.dot(x_train.T,np.multiply(alpha,y_train))
    def __b__(self,i,j,alpha_i_old,alpha_j_old,E_i,E_j):
        b1 = self.b - E_i - self.y_train[i]*(self.alpha[i] - alpha_i_old)*self.K(self.x_train.iloc[i],self.x_train.iloc[i]) - self.y_train[j]*(self.alpha[j] - alpha_j_old)*self.K(self.x_train.iloc[i],self.x_train.iloc[j])
        b2 = self.b - E_j - self.y_train[i]*(self.alpha[i] - alpha_i_old)*self.K(self.x_train.iloc[i],self.x_train.iloc[j]) - self.y_train[j]*(self.alpha[j] - alpha_j_old)*self.K(self.x_train.iloc[j],self.x_train.iloc[j])
        b = b1 if abs(self.alpha[i]) < self.C else (b2 if abs(self.alpha[j]) < self.C else (b1 + b2 )/2)
        return b
    def validate_KKT(self,x_i,y_i,w,b,alpha_i):# vadidating i_th sample
        margin = y_i*(np.dot(w.T,x_i) + b)
        if alpha_i < self.tol:
            return 1 - self.tol <= margin <= 1 + self.tol
        elif alpha_i > self.C - self.tol:
            return margin <= 1
        elif  0 < alpha_i < self.C - self.tol:
            return abs(margin - 1) <= self.tol
    def fit(self,x_train,y_train):
        self.x_train = x_train
        self.y_train = y_train
        m,n = x_train.shape
        self.alpha = np.zeros(m)
        self.w = np.zeros(n)
        self.b = 0
        passes = 0
        while ( passes < self.max_passes):
            no_changed_alphas = 0
            for i in range(m):
                E_i = self.pridict(self.x_train.iloc[i]) - self.y_train[i]
                #if not ( self.validate_KKT(self.x_train.iloc[i],self.y_train[i],self.w,self.b,self.alpha[i])):
                if ( (self.y_train[i]*E_i < - self.tol and self.alpha[i] < self.C) or (self.y_train[i]*E_i > self.tol and self.alpha[i] < 0)):
                    j = i
                    while j == i:
                        j = np.random.randint(0,m)
                    alpha_i_old = self.alpha[i]
                    alpha_j_old = self.alpha[j]
                    E_j = self.pridict(self.x_train.iloc[j]) - self.y_train[j]
                    L = 0
                    H = self.C
                    if self.y_train[i] != self.y_train[j]:
                        L = max(0, self.alpha[j] - self.alpha[i])
                        H = min(self.C, self.C + self.alpha[j] - self.alpha[i])
                    else:
                        L = max(0, self.alpha[i] + self.alpha[j] - self.C)
                        H = min(self.C,self.alpha[i] + self.alpha[j])
                    if L == H:
                        continue
                    #compute second_der
                    eta = 2*self.K(x_train.iloc[i],x_train.iloc[j]) - self.K(x_train.iloc[i],x_train.iloc[i]) - self.K(x_train.iloc[j],x_train.iloc[j])
                    if eta >= 0:
                        continue
                    self.alpha[j] = alpha_j_old - ( y_train[j]*(E_i - E_j)/eta)
                    self.alpha[j] = min(max(self.alpha[j],L),H)
                    self.alpha[i] = alpha_i_old + y_train[i]*y_train[j]*(alpha_j_old - self.alpha[j])
                    self.b = self.__b__(i,j,alpha_i_old,alpha_j_old,E_i,E_j)
                    no_changed_alphas += 1
                self.w = self.__w__(x_train,y_train,self.alpha)
                if no_changed_alphas <= 0:
                    passes += 1
                
        return self.alpha

In [26]:
df = pd.read_csv("dataset\Cardiovascular_Disease_Dataset.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\kumar\AppData\Local\Temp\ipykernel_31784\3084864538.py:1: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_csv("dataset\Cardiovascular_Disease_Dataset.csv")

,patientid,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,103368,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,119250,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,119372,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,132514,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,146211,31,1,1,199,0,0,2,136,0,5.3,3,2,1

In [27]:
df['target'] = df['target'].replace(0,-1)
df.drop(['patientid'],axis= 1,inplace= True)

In [28]:
x = pd.DataFrame(df.drop(['target'],axis = 1))
x.head()

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels
0,53,1,2,171,0,0,1,147,0,5.3,3,3
1,40,1,0,94,229,0,1,115,0,3.7,1,1
2,49,1,2,133,142,0,0,202,1,5.0,1,0
3,43,1,0,138,295,1,1,153,0,3.2,2,2
4,31,1,1,199,0,0,2,136,0,5.3,3,2

In [29]:
y = df.target
y

0      1
1     -1
2     -1
3      1
4      1
      ..
995    1
996   -1
997    1
998    1
999   -1
Name: target, Length: 1000, dtype: int64

In [30]:
ratio = 0.8
train_data = int(ratio*x.shape[0])
x_train, x_test = x[:train_data + 1], x[train_data:]
y_train, y_test = y[:train_data + 1], y[train_data:]
x_train

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels
0,53,1,2,171,0,0,1,147,0,5.3,3,3
1,40,1,0,94,229,0,1,115,0,3.7,1,1
2,49,1,2,133,142,0,0,202,1,5.0,1,0
3,43,1,0,138,295,1,1,153,0,3.2,2,2
4,31,1,1,199,0,0,2,136,0,5.3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...
796,63,1,3,195,347,1,2,107,0,2.4,2,1
797,22,0,3,200,264,0,0,75,0,0.3,0,0
798,22,0,0,127,330,0,1,193,1,1.4,1,1
799,58,1,1,132,136,0,0,181,1,5.4,0,0
800,72,1,2,126,555,1,1,186,1,1.6,2,1

In [31]:

SVM = SVMClassifier1(no_passes= 5)
alpha_optimal = SVM.fit(x_train,y_train)
alpha_optimal


#w_star = SVM.__w__(x_train,y_train,alpha_optimal)

array([ 3.24407279e-04,  1.33496946e-04,  9.67577111e-04,  2.14842692e-03,
        1.97736182e-04,  4.91925155e-05,  1.54366071e-03,  9.64642928e-04,
        2.50558844e-04,  7.44608265e-04,  1.50595629e-04,  0.00000000e+00,
        1.54300218e-03,  1.65641595e-05,  5.29375014e-03,  5.53359734e-04,
        2.18394574e-03,  6.70433606e-03,  2.56252626e-04,  1.46851453e-03,
        0.00000000e+00,  1.01515303e-03,  2.57643863e-04,  3.28051680e-04,
        9.53569101e-04,  8.66286521e-04,  8.01576582e-04,  4.26959486e-04,
        5.27830828e-04,  3.08295768e-06,  0.00000000e+00,  3.17679784e-03,
        1.43307285e-03,  1.68516649e-03,  4.60090903e-05,  4.49632495e-04,
        2.72877311e-03,  4.36477965e-03,  0.00000000e+00,  7.39129419e-04,
        2.81202484e-04,  3.34527115e-03,  1.57524787e-03,  0.00000000e+00,
        2.84000208e-04,  7.71013197e-04,  4.00073120e-03,  3.14549084e-03,
        2.81260253e-04,  3.80518719e-04,  2.91837186e-04,  1.24737812e-05,
        1.67788361e-04,  1.41106467e-03,  3.79701389e-03,  1.62356912e-03,
        1.02246982e-03,  1.48278704e-03,  3.62242095e-04,  1.20789629e-05,
        0.00000000e+00,  4.96449667e-06,  4.12157531e-04,  1.73665561e-03,
        2.41224757e-03,  1.95260708e-03,  5.57448803e-04,  2.43232444e-04,
        1.11135484e-04,  5.70548300e-06,  1.49979183e-05,  3.16873625e-05,
        1.01339307e-03,  1.42577801e-03,  1.30750027e-03,  3.93458951e-05,
        3.28907447e-05,  2.67241873e-03,  2.59921536e-04,  3.08412129e-04,
        1.65906723e-03,  2.22786997e-03,  2.74306079e-04,  0.00000000e+00,
        0.00000000e+00,  4.91378834e-04,  5.30930469e-05,  1.37389683e-03,
        1.22074419e-03,  2.82010161e-03,  3.13199741e-03,  2.26347155e-04,
        1.75015663e-03,  8.59486848e-04,  1.34954550e-04,  5.25373975e-04,
        1.52875086e-03,  4.12324583e-04,  3.75338179e-04,  0.00000000e+00,
        7.02299649e-04,  5.07217006e-04,  2.10085684e-03,  5.30349121e-04,
        1.43115505e-04,  3.12755600e-05,  1.28151012e-03,  8.26960173e-04,
        1.76282569e-03,  1.52478492e-03,  6.64778466e-04,  1.72802327e-04,
        1.43434123e-03,  0.00000000e+00,  3.82294688e-04,  1.28177145e-03,
        1.50705456e-03,  0.00000000e+00,  5.84827991e-04,  1.24617881e-04,
        1.99620483e-03,  6.42435611e-04,  2.39061589e-04,  2.82282136e-03,
        2.77741190e-04,  1.79707712e-04,  1.73951367e-03,  6.12492242e-04,
        9.84185234e-04,  6.65300537e-04,  1.26972841e-03,  1.01769779e-04,
        2.79599331e-03,  3.37783235e-04,  6.21495182e-04,  2.31727873e-03,
        2.26559859e-04,  6.57072668e-06,  1.29316971e-03,  1.55476867e-03,
        6.55293404e-04,  2.17065634e-03,  3.40279338e-04,  2.69506064e-03,
        1.46695339e-04,  9.78875083e-04,  2.16516326e-03,  4.93979403e-03,
        1.54782044e-03,  1.65918415e-03,  5.61941015e-04,  9.56822472e-05,
        1.12938265e-05,  1.85876054e-03,  1.11344346e-03, -4.06575815e-20,
        1.67033878e-03,  0.00000000e+00,  2.66427516e-04,  5.29972965e-04,
        2.02730469e-04,  3.49353456e-04,  4.30550433e-03,  1.25035507e-04,
        0.00000000e+00,  1.01853695e-06,  6.70508710e-04,  1.60214644e-05,
        7.43384618e-05,  4.76006222e-03,  0.00000000e+00,  1.66702609e-03,
        1.58228619e-03,  1.77893462e-03,  4.15099477e-04,  7.89615472e-06,
        0.00000000e+00,  1.13730132e-03,  6.14781087e-03,  6.97403278e-03,
        7.14434178e-05,  0.00000000e+00,  0.00000000e+00,  3.65258450e-04,
        3.86924888e-04,  8.79314390e-03,  3.18973672e-03,  5.35686474e-03,
        2.71189442e-03,  1.27438990e-06,  1.12022369e-04,  0.00000000e+00,
        8.14698563e-05,  5.05093528e-04,  2.06679432e-05,  2.70860268e-03,
        1.28335800e-03,  6.50691166e-05,  8.88931417e-04,  2.19519867e-03,
        1.25737794e-03,  2.74727115e-03,  3.62135148e-04,  1.81675001e-04,
        3.67046666e-04,  1.93673119e-03,  0.00000000e+00,  9.49307327e-05,
        3.67992034e-03,  3.07349365e-04,  3.83892720e-03,  1.32332390e-03,
        4.57163175e-04,  1.01967982e-04,  7.48092798e-04,  2.08757820e-05,
        6.34506051e-04,  1.17240881e-04,  0.00000000e+00,  1.54896473e-04,
        1.48234760e-03,  2.13528777e-04,  1.45967235e-03,  1.55194104e-04,
        4.10564856e-04,  1.88606575e-03,  5.80469802e-04,  7.75696669e-05,
        2.73272795e-04,  3.42014484e-04,  2.74491239e-03,  1.03034797e-03,
        1.36509959e-03,  1.44601222e-03,  4.64071105e-04,  6.22725367e-04,
        4.48734421e-04,  1.23623739e-04,  5.19808188e-04,  3.15382223e-03,
        3.31853281e-03,  5.31783166e-04,  2.76604971e-03,  5.63258900e-04,
        1.07110219e-04,  2.04429394e-04,  3.40648999e-03,  3.85053551e-05,
        3.02526456e-04,  0.00000000e+00,  4.13867221e-04,  0.00000000e+00,
        2.80689620e-03,  1.54679855e-04,  2.73443449e-04,  6.53138529e-03,
        4.02149339e-04,  1.34084176e-03,  5.02027836e-04,  3.80413980e-04,
        8.51925111e-04,  1.75806446e-04,  3.47456910e-03,  0.00000000e+00,
        1.53855623e-03,  7.35835277e-04,  3.18260768e-05,  2.01909978e-03,
        6.11605124e-06,  3.28098242e-03,  6.56560090e-05,  6.74069935e-04,
        0.00000000e+00,  0.00000000e+00,  2.41624020e-04,  5.24254822e-04,
        3.42855096e-03,  7.14767857e-04,  3.01722387e-04,  1.47889017e-03,
        1.00011926e-03,  0.00000000e+00,  0.00000000e+00,  2.23284970e-03,
        4.18799753e-04,  3.18990361e-03,  3.44299328e-05,  1.64875703e-03,
        5.15267696e-04,  6.92907702e-04,  8.88296257e-07,  1.89179010e-04,
        3.53646445e-04,  6.49230385e-03,  3.04912310e-04,  1.65516969e-03,
        0.00000000e+00,  2.90428166e-03,  1.21958019e-03,  2.07690863e-04,
        6.19223549e-04,  0.00000000e+00,  2.35045339e-04,  1.81436150e-03,
        5.04607645e-03,  2.72934053e-04,  1.09798159e-04,  6.63589706e-04,
        5.26818880e-04,  0.00000000e+00,  1.12158069e-04,  2.92878708e-04,
        0.00000000e+00,  2.10822272e-03,  6.50969287e-05,  1.08626842e-04,
        2.55933583e-04,  7.77688043e-05,  1.06099493e-04,  3.92420894e-04,
        2.14218899e-04,  7.30458947e-04,  8.48967486e-04,  6.09857089e-04,
        1.93309135e-03,  4.77854689e-04,  4.98165785e-05,  3.20475813e-03,
        2.15281155e-04,  2.45802409e-04,  2.88554128e-04,  9.97537750e-04,
        5.87664460e-04,  0.00000000e+00,  2.71050543e-20,  5.09684117e-05,
        3.86709279e-03,  2.20130022e-03,  8.58051400e-04,  2.40982445e-03,
        0.00000000e+00,  0.00000000e+00,  4.38817755e-06,  3.61822509e-04,
        1.75181467e-03,  0.00000000e+00,  4.25077627e-05,  1.30432307e-04,
        9.42387847e-04,  7.03660067e-04,  2.59829712e-04,  4.13362554e-04,
        7.75304299e-04,  7.88319296e-05,  1.63166453e-05,  8.21874552e-06,
        2.59023306e-03,  4.33502330e-03,  1.80828449e-03,  8.11548458e-05,
        1.20879671e-04,  1.73670196e-04,  1.18809825e-03,  1.44811506e-05,
        9.56504826e-04,  2.49495207e-03,  6.40548561e-04,  8.18505802e-04,
        2.94770876e-03,  4.17300200e-04,  1.68959678e-03,  8.70947891e-04,
        1.14953178e-03,  2.76447138e-03,  0.00000000e+00,  1.38276620e-04,
        3.33379994e-05,  9.71289240e-04,  2.17479575e-04,  3.27992607e-05,
        3.28481429e-03,  0.00000000e+00,  8.78700525e-04,  9.22250021e-04,
        1.28883244e-04,  1.94186053e-03,  5.01713902e-04,  3.06304193e-03,
        7.35274270e-04,  1.41863615e-04,  2.28244767e-03,  1.10335416e-03,
        1.85927091e-03,  1.36348748e-04,  6.07983884e-05,  0.00000000e+00,
        1.83259047e-03,  1.38148503e-04,  4.33025121e-03,  1.51474998e-03,
        2.37176697e-04,  0.00000000e+00,  2.38828154e-03,  5.77459302e-05,
        3.95397657e-03,  1.50255297e-03,  7.48239531e-04,  1.14318990e-03,
        1.64395311e-04,  6.87891748e-05,  2.85524765e-03,  7.48399762e-04,
        2.18904914e-04,  1.19966096e-04,  2.28603719e-03,  6.72159921e-06,
        7.15544344e-05,  1.20584682e-03,  4.23671934e-03,  7.13631833e-04,
        3.27574500e-05,  2.25400295e-04,  0.00000000e+00,  7.70796467e-04,
        8.97459685e-05,  1.67929532e-03,  2.96890812e-04,  0.00000000e+00,
        2.49369031e-03,  7.43491597e-03,  2.24900608e-04,  1.69500825e-04,
        5.20255291e-04,  2.20779889e-03, -3.38813179e-21,  1.11793778e-03,
        3.77099473e-04,  2.99696917e-04,  6.07502666e-04,  1.09698990e-03,
        2.32613407e-04,  5.48457927e-03,  3.18993196e-04,  4.11884704e-03,
        1.16944528e-04,  7.58309441e-04,  1.60198525e-03,  2.34554635e-04,
        5.83571524e-04,  3.41023417e-04,  5.97727577e-05,  1.85999492e-03,
        2.77675574e-03,  2.86216911e-04,  2.91846716e-04,  4.65683263e-03,
        6.40028163e-06,  2.15055043e-03,  4.58602545e-03,  2.63108880e-05,
        7.17514919e-04,  2.08557663e-03,  0.00000000e+00,  1.51813200e-03,
        1.93641012e-03,  2.60273945e-03,  5.73811504e-04,  1.63559971e-03,
        7.19943819e-04,  8.53739099e-04,  2.35374262e-04,  0.00000000e+00,
        3.65763862e-06,  2.92799157e-04,  5.14327883e-04,  3.70051248e-04,
        6.15684196e-03,  4.07547211e-03,  2.90469011e-03,  6.61662134e-04,
        3.74758529e-03,  9.63227034e-04,  2.05844538e-03,  1.19846521e-03,
        4.99146877e-03,  2.26081979e-03,  3.59852423e-04,  1.54877977e-03,
        7.05979341e-04,  1.86886624e-04,  2.72717615e-04,  7.70084540e-05,
        4.34724804e-04,  7.47504710e-04,  1.77253592e-04,  2.22795571e-03,
        1.66947216e-03,  8.80054086e-04,  9.19364089e-04,  0.00000000e+00,
        2.22679915e-05,  1.06815923e-04,  3.49727387e-03,  2.20912553e-03,
        2.15174440e-03,  6.31812281e-04,  8.58763213e-04,  4.13124252e-04,
        3.58405341e-03,  1.26148992e-03,  0.00000000e+00,  1.57277387e-05,
        0.00000000e+00,  6.95726607e-04,  7.35310350e-04,  3.32743815e-03,
        1.07228937e-04,  2.85830514e-03,  3.11395957e-04,  9.20630276e-06,
        9.29220772e-05,  1.07905297e-03,  1.88223766e-03,  6.40663108e-05,
        7.81226956e-05,  4.64590393e-04,  1.69681032e-04,  4.04557021e-04,
        9.72123357e-05,  1.23872513e-03,  4.59643798e-03,  2.23616698e-19,
        1.73542840e-03,  8.28121228e-05,  1.75781298e-03,  4.19790976e-04,
        1.95112529e-04,  8.15353483e-05,  4.04945197e-03,  6.57553440e-04,
        6.71344662e-04,  1.35525272e-20,  3.51500399e-04,  3.18297208e-03,
        0.00000000e+00,  4.65053784e-05,  1.38592516e-03,  0.00000000e+00,
        0.00000000e+00,  2.49200220e-03,  0.00000000e+00,  8.54708062e-04,
        4.96739054e-04,  0.00000000e+00,  1.33843851e-04,  3.85280796e-04,
        2.25102529e-04,  0.00000000e+00,  2.64535517e-05,  2.00574656e-03,
        3.34008062e-04,  8.37439404e-04,  1.45382461e-04,  7.23936159e-04,
        5.81366493e-05,  3.60270486e-04,  0.00000000e+00,  1.18977320e-03,
        2.03421478e-03, -1.60936260e-20,  1.49417916e-03,  3.56739998e-03,
        0.00000000e+00,  2.19590718e-03,  1.18634111e-03,  2.41032212e-05,
        0.00000000e+00,  9.55343929e-06,  4.52883918e-05,  1.60201216e-03,
        2.28785549e-03,  1.47162983e-03,  2.39335615e-04,  4.65449148e-04,
        3.63387430e-07,  2.87564330e-03,  8.04959947e-04,  2.04216106e-04,
        1.15530994e-04,  1.41561137e-04,  2.58069859e-04,  1.31525639e-03,
        4.66010079e-03,  1.52810524e-05,  1.26378385e-03,  0.00000000e+00,
        1.95371625e-04,  2.01734994e-03,  3.10558686e-03,  1.36984113e-04,
        1.81840662e-04,  0.00000000e+00,  1.48327614e-02,  2.08946077e-04,
        3.84823524e-04,  5.74711076e-04,  1.41645480e-03,  5.61989515e-06,
        1.00512030e-03,  1.35138154e-03,  3.12250878e-04,  7.30832055e-04,
        3.91163869e-04,  1.31509508e-03,  7.09914024e-05,  5.45610068e-04,
        3.96280592e-04,  2.21629011e-03,  9.97379821e-04,  3.14065994e-04,
        9.30633502e-04,  6.62628086e-04,  0.00000000e+00,  3.37632690e-04,
        2.36678701e-03,  2.70192061e-04,  1.13020667e-03,  1.14721964e-03,
        6.95320411e-04,  2.00965340e-03,  5.63197445e-05,  8.25976586e-04,
        2.76549762e-04,  3.16087784e-04,  2.00916916e-03,  1.61374444e-03,
        0.00000000e+00,  1.82403493e-04,  3.74751542e-04,  0.00000000e+00,
        1.41183264e-05,  2.52622132e-03,  1.38427495e-03,  0.00000000e+00,
        2.68350519e-04,  1.29078166e-03,  1.03087445e-03,  2.87682502e-03,
        8.61940973e-04,  1.10270552e-03,  4.29206322e-04,  0.00000000e+00,
        2.46519151e-05,  2.21855794e-04,  8.79357189e-04,  5.45565191e-03,
        2.03557849e-05,  3.82602316e-05,  1.48362055e-03,  1.80028199e-03,
        6.08632701e-03,  1.18700494e-03,  3.82368999e-04,  3.43348432e-03,
        3.07573406e-03,  7.66639514e-04,  1.95469720e-03,  2.90755882e-04,
        4.25805854e-03,  6.41165235e-05,  3.02116929e-04,  1.28303148e-03,
        7.55801398e-04,  1.95363928e-03,  1.60532815e-03,  1.71032643e-03,
        1.88524082e-03,  2.38963439e-04,  1.39194628e-03,  1.34806571e-03,
        3.01342539e-04,  6.43908656e-04,  0.00000000e+00,  4.15279793e-03,
        2.61887445e-04,  2.00076360e-03,  2.66371775e-03,  1.26718326e-05,
        8.57465768e-05,  1.64142744e-03,  1.37303055e-04,  1.12332497e-03,
        0.00000000e+00,  0.00000000e+00,  5.35432074e-05,  6.60885326e-04,
        3.41213717e-04,  0.00000000e+00,  1.21928863e-03,  0.00000000e+00,
        2.44296216e-03,  4.18635677e-04,  1.00027832e-05,  0.00000000e+00,
        8.13056949e-05,  8.56325117e-04,  4.12939432e-04,  2.68921435e-04,
        1.03861250e-03,  4.20624597e-04,  2.82002588e-03,  0.00000000e+00,
        1.62267697e-03,  5.40121328e-04,  9.96968424e-04,  5.71949522e-05,
        1.72926532e-03,  9.53237469e-05,  7.38558612e-04,  0.00000000e+00,
        2.72721737e-04,  2.06757026e-03,  2.07676423e-04,  1.90821047e-05,
        6.83376241e-04,  2.81319622e-03,  4.96209990e-04,  2.32368913e-03,
        1.69787188e-03,  3.50921700e-06,  0.00000000e+00,  3.67399468e-03,
        2.20790982e-04,  2.28088857e-04,  0.00000000e+00,  4.88917240e-04,
        3.35960504e-04,  4.82495918e-04,  4.03181664e-03,  1.01540051e-03,
        5.30899650e-03,  3.02507051e-04,  1.93893062e-04,  5.01786960e-05,
        2.69021856e-04,  9.72694723e-05,  4.84517831e-03,  2.81411574e-04,
        1.00556074e-03,  2.14035700e-03,  9.58706678e-03,  1.53242987e-05,
        1.61183711e-03,  1.34258171e-04,  1.28607633e-05,  3.15388460e-03,
        5.62089908e-04,  1.00802373e-03,  4.92283857e-04,  1.85723157e-04,
        2.63478340e-04,  3.42424323e-04,  1.71477839e-04,  3.05911277e-05,
        1.21007262e-03,  4.54687183e-04,  3.86612774e-04,  1.55061902e-03,
        8.68000741e-05,  2.98227034e-03,  3.20520514e-03,  5.19813870e-04,
        2.18359204e-04,  9.09819756e-04,  0.00000000e+00,  2.36191252e-04,
        1.21683535e-04,  2.28757618e-05,  8.00920181e-04,  2.49231918e-04,
        1.14346026e-03,  4.36592241e-04,  1.53732443e-05,  1.94145834e-03,
        4.40457133e-20,  1.92064358e-03,  1.14178595e-04,  5.49631109e-04,
        0.00000000e+00,  5.09493336e-04,  1.53037740e-04,  0.00000000e+00,
        1.21492010e-04, -1.49077799e-19,  0.00000000e+00,  0.00000000e+00,
        5.18562374e-05,  9.49128237e-04,  7.39122036e-04,  4.05382396e-04,
        5.88141267e-05])

In [33]:
m,n = x_train.shape
count = 0
for i in range(800,1000):
  if (SVM.pridict(x.iloc[i])*y[i]) > 0:
    count += 1
count

136